export const mashhadEvents = [
  {
    id: "rad-e-zaman",
    title: "نمایشگاه گروهی عکس «رد زمان»",
    category: "هنرهای تجسمی",
    date: "۷ تا ۱۱ شهریور ۱۴۰۵",
    time: "۱۷ تا ۲۰",
    venue: "نگارخانه فردوسی، مجتمع شریعتی جهاد دانشگاهی",
    sourceLabel: "فرهنگسرای جهاد دانشگاهی",
    sourceUrl: "https://telemetr.io/fa/channels/1001833193-farhangsarajahad",
  },
  {
    id: "art-of-war",
    title: "نشست مهرگان کتاب؛ بازشناسی «هنر جنگ»",
    category: "کتاب و گفت‌وگو",
    date: "۱۵ شهریور ۱۴۰۵",
    time: "۱۸:۰۰",
    venue: "کتابفروشی جهاد دانشگاهی، میدان آزادی",
    price: "رایگان با ثبت‌نام قبلی",
    sourceLabel: "فرهنگسرای جهاد دانشگاهی",
    sourceUrl: "https://telemetr.io/fa/channels/1001833193-farhangsarajahad",
  },
  {
    id: "maze-tech-product",
    title: "هزارتوی تک و پروداکت",
    category: "فناوری و محصول",
    date: "۱۹ شهریور ۱۴۰۵",
    venue: "کارخانه نوآوری مشهد",
    sourceLabel: "هزارتو مدیا",
    sourceUrl: "https://hezartoo.media/",
    imageUrl: "https://hezartoo.media/wp-content/uploads/2026/07/banner-Tech-and-Product2-1024x576.jpg",
    imageAlt: "پوستر رویداد هزارتوی تک و پروداکت",
  },
  {
    id: "autumn-fair",
    title: "نمایشگاه عرضه مستقیم کالای پاییزه",
    category: "نمایشگاه",
    date: "۲۶ تا ۳۱ شهریور ۱۴۰۵",
    venue: "نمایشگاه بین‌المللی مشهد",
    sourceLabel: "مدیریت پروژه‌های نمایشگاهی",
    sourceUrl: "https://epma.ir/new/paez/",
    imageUrl: "https://epma.ir/new/wp-content/themes/iranenaz/files/images/header.jpg",
    imageAlt: "نمای معرفی مدیریت پروژه‌های نمایشگاهی",
  },
  {
    id: "philosophy-cafe",
    title: "کافه فلسفه؛ انتخاب و مسئولیت",
    category: "گفت‌وگو و ارتباط",
    date: "۱۹ شهریور ۱۴۰۵",
    time: "۱۸:۳۰",
    venue: "مشهد",
    price: "رایگان",
    sourceLabel: "قبیله",
    sourceUrl: "https://ghabilee.ir/",
    imageUrl: "https://ghabilee.ir/_next/image?q=75&url=%2Fimages%2Fdefaults%2Fevent-fallback-portrait.avif&w=3840",
    imageAlt: "تصویر رویداد در سامانه قبیله",
  },
  {
    id: "social-documentary",
    title: "نمایش و نقد مستند اجتماعی",
    category: "هنر و فرهنگ",
    date: "۲ مهر ۱۴۰۵",
    time: "۱۸:۰۰",
    venue: "مشهد",
    sourceLabel: "قبیله",
    sourceUrl: "https://ghabilee.ir/",
    imageUrl: "https://ghabilee.ir/_next/image?q=75&url=%2Fimages%2Fdefaults%2Fevent-fallback-portrait.avif&w=3840",
    imageAlt: "تصویر رویداد در سامانه قبیله",
  },
];
